version: "3.9"

services:
  db:
    image: pgvector/pgvector:pg16
    container_name: chat_db
    restart: always
    env_file:
      - ./backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    container_name: backend
    command:
      [
        "./wait-for-it.sh",
        "db:5432",
        "--",
        "python",
        "manage.py",
        "runserver",
        "0.0.0.0:8000",
      ]
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    environment:
      - DEBUG=True
      - ENV=development

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: http://localhost:8000/api
    container_name: frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_API_BASE_URL=http://localhost:8000/api
    command: npm run dev
    stdin_open: true
    tty: true

  worker:
    build:
      context: ./backend
    container_name: backend_worker
    command:
      [
        "./wait-for-it.sh",
        "db:5432",
        "--",
        "python",
        "manage.py",
        "process_sync_jobs",
      ]
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    environment:
      - DEBUG=True
      - ENV=development
    depends_on:
      - db

volumes:
  postgres_data:
