# Generated by Django 5.2 on 2025-05-03 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatBotInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('is_helpful', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chatBot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='chat.chatbotinstance')),
            ],
        ),
        migrations.AddField(
            model_name='chatbotinstance',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatBots', to='chat.company'),
        ),
        migrations.CreateModel(
            name='ConfluenceSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space_url', models.URLField()),
                ('last_sync_time', models.DateTimeField(blank=True, null=True)),
                ('chatBot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confluenceSyncs', to='chat.chatbotinstance')),
            ],
        ),
        migrations.CreateModel(
            name='JiraSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_url', models.URLField()),
                ('last_sync_time', models.DateTimeField(blank=True, null=True)),
                ('chatBot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jiraSyncs', to='chat.chatbotinstance')),
            ],
        ),
    ]
