# Generated by Django 5.2 on 2025-06-04 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_credential_confluencesync_credential_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfluencePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('url', models.URLField()),
                ('last_updated', models.DateTimeField()),
                ('sync', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='chat.confluencesync')),
            ],
        ),
        migrations.CreateModel(
            name='JiraIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_key', models.CharField(max_length=100)),
                ('summary', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('sync', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='chat.jirasync')),
            ],
        ),
        migrations.CreateModel(
            name='JiraComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='chat.jiraissue')),
            ],
        ),
    ]
