# Generated by Django 5.2 on 2025-06-05 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_confluencepage_jiraissue_jiracomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='email',
            field=models.EmailField(default='bretfarve24@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
