# Generated by Django 5.2 on 2025-09-02 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_credential_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='confluencesync',
            name='sync_interval',
            field=models.CharField(choices=[('manual', 'Manual'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='manual', max_length=10),
        ),
        migrations.AddField(
            model_name='jirasync',
            name='sync_interval',
            field=models.CharField(choices=[('manual', 'Manual'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='manual', max_length=10),
        ),
    ]
