# Generated by Django 5.2 on 2025-09-09 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_confluencesync_sync_interval_jirasync_sync_interval'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('github_username', models.CharField(max_length=255)),
                ('_token', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gitCredentials', to='chat.company')),
            ],
        ),
        migrations.CreateModel(
            name='GitRepoSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_full_name', models.CharField(max_length=300)),
                ('branch', models.CharField(default='main', max_length=100)),
                ('last_sync_time', models.DateTimeField(blank=True, null=True)),
                ('sync_interval', models.CharField(choices=[('manual', 'Manual'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='manual', max_length=10)),
                ('chatBot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gitRepoSyncs', to='chat.chatbotinstance')),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repoSyncs', to='chat.gitcredential')),
            ],
        ),
        migrations.CreateModel(
            name='GitRepoFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=2000)),
                ('sha', models.CharField(max_length=100)),
                ('size', models.IntegerField()),
                ('url', models.URLField()),
                ('content', models.TextField()),
                ('last_updated', models.DateTimeField()),
                ('sync', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='chat.gitreposync')),
            ],
            options={
                'unique_together': {('sync', 'path')},
            },
        ),
    ]
