# Generated by Django 5.2 on 2025-09-15 01:45

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_gitcredential_gitreposync_gitrepofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('jira', 'Jira'), ('confluence', 'Confluence'), ('gitHub', 'GitHub')], max_length=50)),
                ('source_id', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.company')),
            ],
        ),
    ]
