# Generated by Django 5.2 on 2025-09-18 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='chatbot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chat.chatbotinstance'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='source',
            field=models.CharField(choices=[('jira', 'Jira'), ('confluence', 'Confluence'), ('github', 'GitHub')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('company', 'source', 'source_id')},
        ),
    ]
