# Generated by Django 5.2 on 2025-10-05 22:02

from django.db import migrations, models


def forwards(apps, schema_editor):
    Document = apps.get_model("chat", "Document")
    Document.objects.filter(source="jira").update(source="jira_issue")


def backwards(apps, schema_editor):
    Document = apps.get_model("chat", "Document")
    Document.objects.filter(source="jira_comment").update(source="jira")
    Document.objects.filter(source="jira_issue").update(source="jira")


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0008_document_chatbot_alter_document_source_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="source",
            field=models.CharField(
                choices=[
                    ("jira_issue", "Jira Issue"),
                    ("jira_comment", "Jira Comment"),
                    ("confluence", "Confluence"),
                    ("github", "GitHub"),
                ],
                max_length=50,
            ),
        ),
        migrations.RunPython(forwards, backwards),
    ]
