# Generated by Django 5.2 on 2025-10-06 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0009_alter_document_source"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="document",
            unique_together={("company", "chatbot", "source", "source_id")},
        ),
    ]
